pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION = 'true'
    }

    stages {
        stage('Init') {
            steps {
                withCredentials([
                    string(credentialsId: 'hcp-terraform-token', variable: 'TF_TOKEN_app_terraform_io'),
                    file(credentialsId: 'gcp-plan-sa-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')
                ]) {
                    dir('gcp-static-website') {
                        sh 'terraform init'
                        sh 'terraform fmt -check -recursive'
                        sh 'terraform validate'
                        sh 'tflint --recursive'
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                withCredentials([
                    string(credentialsId: 'hcp-terraform-token', variable: 'TF_TOKEN_app_terraform_io'),
                    file(credentialsId: 'gcp-plan-sa-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                    file(credentialsId: 'ssl-certificate-file', variable: 'TMP_CERT_PATH'),
                    file(credentialsId: 'ssl-private-key-file', variable: 'TMP_KEY_PATH')
                ]) {
                    dir('gcp-static-website') {
                        sh 'cp $TMP_CERT_PATH ./cert.pem'
                        sh 'cp $TMP_KEY_PATH ./key.pem'

                        sh 'TF_VAR_ssl_certificate_path="./cert.pem" TF_VAR_ssl_private_key_path="./key.pem" terraform plan -out=tfplan'
                    }
                }
            }
        }
        stage('Approval') {
            steps {
                input message: 'Apply changes?'
            }
        }
        stage('Apply') {
            steps {
                withCredentials([
                    string(credentialsId: 'hcp-terraform-token', variable: 'TF_TOKEN_app_terraform_io'),
                    file(credentialsId: 'gcp-apply-sa-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                    file(credentialsId: 'ssl-certificate-file', variable: 'TMP_CERT_PATH'),
                    file(credentialsId: 'ssl-private-key-file', variable: 'TMP_KEY_PATH')
                ]) {
                    dir('gcp-static-website') {
                        sh 'cp $TMP_CERT_PATH ./cert.pem'
                        sh 'cp $TMP_KEY_PATH ./key.pem'

                        sh 'terraform apply -auto-approve tfplan'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}