apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}   
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ include "k8s-troubleshooting-ae.fullname" . }}-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role             
                    operator: In
                    values:
                      - production            
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_MODE
              value: {{ required "APP_MODE is required, set .Values.app.mode" .Values.app.mode | quote }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config            
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 80                       
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80                      
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
