namespace: k8s-troubleshooting-ae

app:
  name: troubleshooting-app
  image:
    repository: nginx
    tag: "1.27-alpine"
  mode: "production"
  replicas: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nameOverride: ""
fullnameOverride: ""

networkPolicy:
  enabled: false


