modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200]
      method: GET
  http_4xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [400, 404]
      method: GET