apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.paymentApi.replicas }}
  selector:
    matchLabels:
      {{- include "payments.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "payments.labels" . | nindent 8 }}
        {{- include "payments.api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: payment-api
          image: {{ .Values.paymentApi.image.repository }}:{{ .Values.paymentApi.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_DB_URL
              value: jdbc:postgresql://{{ .Values.db.endpoint }}/{{ .Values.db.name }}
            - name: PAYMENT_DB_USER
              value: {{ .Values.db.user | quote }}
            - name: PAYMENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-db
                  key: password
            - name: PAYMENT_WORKER_BASE_URL
              value: http://payment-worker:8090
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          {{- with .Values.paymentApi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
