{{- if .Values.paymentWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.paymentWorker.replicas }}
  selector:
    matchLabels:
      {{- include "payments.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "payments.labels" . | nindent 8 }}
        {{- include "payments.worker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: payment-worker
          image: {{ .Values.paymentWorker.image.repository }}:{{ .Values.paymentWorker.image.tag }}
          ports:
            - containerPort: 8090
          env:
            - name: PAYMENT_API_BASE_URL
              value: http://payment-api:8080
            - name: PAYMENT_WORKER_PORT
              value: "8090"
            - name: WORKER_CPU_LOAD_MS
              value: {{ .Values.paymentWorker.cpuLoadMs | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          {{- with .Values.paymentWorker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
