apiVersion: v1
kind: Secret
metadata:
  name: payments-db
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.db.password | quote }}