apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "payments.api.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: 8080
---
{{- if .Values.paymentWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: payment-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payments.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  selector:
    {{- include "payments.worker.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8090
      targetPort: 8090
{{- end }}
