namespace: payments

db:
  endpoint: ""
  name: payments
  user: payments
  password: ""

paymentApi:
  replicas: 2
  image:
    repository: ""
    tag: latest

paymentWorker:
  replicas: 2
  image:
    repository: ""
    tag: latest
  cpuLoadMs: 500